# Generated by Django 5.1 on 2024-12-01 07:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapDate', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(default=2024)),
                ('top_artist', models.CharField(default='Unknown', max_length=500)),
                ('top_songs', models.JSONField(default=list)),
                ('image_url', models.TextField(default=None)),
                ('top_3_artists', models.TextField(default=list)),
                ('artist1', models.CharField(default='Unknown', max_length=500)),
                ('artist2', models.CharField(default='Unknown', max_length=500)),
                ('artist3', models.CharField(default='Unknown', max_length=500)),
                ('song_artist1', models.TextField(default='Unknown')),
                ('song_artist2', models.TextField(default='Unknown')),
                ('song_artist3', models.TextField(default='Unknown')),
                ('song_artist4', models.TextField(default='Unknown')),
                ('song_artist5', models.TextField(default='Unknown')),
                ('song_artist6', models.TextField(default='Unknown')),
                ('mood1', models.CharField(default='Unknown', max_length=500)),
                ('mood2', models.CharField(default='Unknown', max_length=500)),
                ('mood3', models.CharField(default='Unknown', max_length=500)),
                ('mood4', models.CharField(default='Unknown', max_length=500)),
                ('mood5', models.CharField(default='Unknown', max_length=500)),
                ('mood6', models.CharField(default='Unknown', max_length=500)),
                ('image', models.TextField(default=None)),
                ('season', models.CharField(default='Seasonal', max_length=20)),
                ('content', models.TextField(default=None)),
                ('hindi_content', models.TextField(default='Unknown')),
                ('mandarin_content', models.TextField(default='Unknown')),
                ('mood', models.CharField(default='Unknown', max_length=500)),
                ('songPath', models.TextField(default=None)),
                ('latest_time', models.CharField(default='Unknown', max_length=500)),
                ('time_ranges', models.JSONField(default=dict)),
                ('total_minutes', models.FloatField(default=0)),
                ('hour_hand_rotation', models.FloatField(default=0)),
                ('minute_hand_rotation', models.FloatField(default=0)),
                ('premium', models.BooleanField(default=False)),
                ('ads_minutes', models.FloatField(default=0)),
                ('holiday', models.CharField(default='none', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wraps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
