# Generated by Django 5.1.1 on 2024-11-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UnWrapped", "0002_remove_customwrap_ad_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customwrap",
            name="top_songs_6_month",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="customwrap",
            name="top_songs_month",
            field=models.JSONField(default=dict),
        ),
    ]
