# Generated by Django 5.1.1 on 2024-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UnWrapped", "0002_customwrap_hindi_mood1_customwrap_hindi_mood2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customwrap",
            name="top_songs_artists",
            field=models.JSONField(default=list),
        ),
    ]
