# Generated by Django 5.1.1 on 2024-11-22 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UnWrapped", "0003_alter_customwrap_top_songs_6_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customwrap",
            name="top_songs_6_month",
        ),
        migrations.RemoveField(
            model_name="customwrap",
            name="top_songs_month",
        ),
    ]
