# Generated by Django 5.1.1 on 2024-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UnWrapped", "0004_customwrap_top_songs_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="customwrap",
            name="imagePath",
            field=models.TextField(default="Unknown"),
        ),
    ]
