# Generated by Django 5.1.1 on 2024-11-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UnWrapped", "0004_remove_customwrap_top_songs_6_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customwrap",
            name="wrapDate",
            field=models.DateTimeField(),
        ),
    ]
