# Generated by Django 5.1.1 on 2024-11-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UnWrapped", "0006_alter_customwrap_wrapdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customwrap",
            name="wrapDate",
            field=models.DateTimeField(),
        ),
    ]
